# Generated by Django 4.0.5 on 2022-06-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_companies_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='size',
            field=models.IntegerField(),
        ),
    ]
