# Generated by Django 4.0.5 on 2022-06-22 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='article',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='campany_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.companies'),
        ),
    ]
