# Generated by Django 4.0.5 on 2022-06-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_review_campany_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='job_title',
            field=models.CharField(max_length=254),
        ),
    ]
